package ProjectEuler.solutions;

/**
 * Even Fibonacci numbers
 *
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class EvenFibonacciNumbers {
    public static long findEvenFibSum(long target){
        long f1 = 0;
        long f2 = 1;
        long f3 = f1+f2;
        long sum = 0;
        while (f3<target){
            if(f3%2 == 0){
                sum+=f3;
            }
            f1=f2;
            f2=f3;
            f3=f1+f2;
        }
        return sum;
    }
    public static void main(String args[]){
        System.out.println(findEvenFibSum(4000000));
    }
}
